package crush

import (
	"encoding/base64"
	"math/bits"
)

// These are the odd entries of Ceph v20.2.4's __RH_LH_tbl and all of
// __LL_tbl, encoded big-endian. The even reciprocal entries are exactly
// ceil(2^55/(128+k)) and are computed in crushLn.
const crushLnLHBase64 = "AAAAAAAAAAAAAALfyhbd4QAABbnloXC0AAAIjmjqiZoAAAtdabrHfgAADib9XIVV" +
	"AAAQ6zifop8AABOqL90n8QAAFmP2+skTAAAZGKFuRjMAABvIQkCtqwAAHnLsEX+l" +
	"AAAhGLEZtPMAACO5oy6qVgAAJlXTxPFcAAAo7VPzB+4AACuANHP3rQAALg6Fqd4E" +
	"AAAwmFegXgcAADMdug784QAANZ68W2nZAAA4G22bspsAADqT3JhksgAAPQgXzpzU" +
	"AAA/eC1yBNAAAEHkK27AwAAAREwfa0wtAABGsBbKR8EAAEkQHqw4HAAAS2xD8TZq" +
	"AABNxJM6kzcAAFAZGOxsEQAAUmnhLzRuAABUtvfxMloAAFcAaOfvWgAAWUY/kZ3u" +
	"AABbiIc2dDMAAF3HSun77AAAYAKVjFhxAABiOnHLgsgAAGRu6iR8XAAAZqAI5HiM" +
	"AABozdgp/YEAAGr4YeX8fQAAbR+v3OIKAABvQ8unnkAAAHFkvrSlbQAAc4KSSOlh" +
	"AAB1nU+Ay6gAAHe0/1EI2QAAecmqh51TAAB721nMo4gAAH3qFaMsGwAAf/Xmag/+" +
	"AACB/tRcvMsAAIQE55P7gQAAhggoBrHVAACICJ2KnkcAAIoGT9UPKgAAjAFGe5S7" +
	"AACN+Yj0roAAAI/vHph0CQAAkeIOoTk+AACT0mAsLl8AAJXAGjn71gAAl6tDr1n5" +
	"AACZk+NVpOUAAJt5/9tsiwAAnV2f1QELAACfPsm8+4AAAKEdg/TDVQAAovnUxRA5" +
	"AACk08JeaNwAAKarUtmedgAAqICMOEVHAACqU3RlKhwAAKwkETTE6QAArfJoZaih" +
	"AACvvn+g8E0AALGIXHqpggAAs1AEcjxGAAC1FXzy0HgAALbYy1OwygAAuJn02Ktj" +
	"AAC6WP6ycDoAALwV7f7tMgAAvdDHyagXAAC/iZEMFngAAMFATq3zgwAAwvUFhZPZ" +
	"AADEp7pYN3wAAMZYcdpZ3QAAyAcwsAAWAADJs/ttBVkAAMte1pVlrwAAzQfGnYcC" +
	"AADOrs/qgIUAANBT9tJgiQAA0fc/nHDAAADTmK6BeQYAANU4R6wApgAA1tYPOI5B" +
	"AADYcgk15kMAANoMOaVIBAAA26SkeqmWAADdO02c8ksAAN7QOOYz8wAA4GNqI+Lu" +
	"AADh9OUXDQIAAOOErXSPDgAA5RLG5UmYAADmnzUGVEgAAOgp+2kwRAAA6bMdk/mO" +
	"AADrOp8Bl1AAAOzAgyHrMAAA7kTNWf+rAADvx4EENXkAAPFIoXBwCgAA8sgx5EEW" +
	"AAD0RjWbE1MAAPXCr8ZURwAA9z2jjZ1KAAD4txQO27EAAPovBF54MgAA+6V3h319" +
	"AAD9GnCLvhEAAP6N8mP5VwAA//8AAAAA"

const crushLnLLBase64 = "AAAAAAAAAAAAAAAC4qYKAAAAAAcMtk7FAAAACe9QzmcAAAAM0eWI/QAAAA+0dH6c" +
	"AAAAEpb9r14AAAAVeYEbWAAAABhb/sKhAAAAGz52pVIAAAAeIOjDgAAAACEDVR1D" +
	"AAAAI+W7srIAAAAmyByD5AAAACmqd5DwAAAALIzM2e0AAAAvbxxe8gAAADJRZiAX" +
	"AAAANTOqHXEAAAA4FehXGgAAADr4IM0mAAAAPdpTf64AAABAvIBuyAAAAEOep5qM" +
	"AAAARoDJAxAAAABJYuSobAAAAExE+oq2AAAATycKqgYAAABSCRUGcgAAAFTrGaAT" +
	"AAAAV80Ydv0AAABarxGLSgAAAF2RBN0PAAAAYHLybGQAAABjVNo5YAAAAGY2vEQa" +
	"AAAAaRiYjKgAAABr+m8TIgAAAG7cP9efAAAAcb4K2jUAAAB0n9Aa/QAAAHeBj5oM" +
	"AAAAemNJV3oAAAB9RP1TXgAAAIAmq43OAAAAgwhUBuMAAACF6fa+sgAAAIjLk7VS" +
	"AAAAi60q6twAAACOjrxfZQAAAJFwSBMFAAAAlFHOBdMAAACXM0435QAAAJoUyKlT" +
	"AAAAnPY9WjMAAACf16xKnQAAAKKwfzRYAAAApZp46moAAACoe9aZ+wAAAKtdLolw" +
	"AAAArj6AuOMAAACxH80oaQAAALQBE9gYAAAAtuJUyAoAAAC5w4/4UwAAALykxWkM" +
	"AAAAv4X1GkoAAADCZx8MJgAAAMVIQz62AAAAyClhshEAAADLCnpmTQAAAM3rjVuC" +
	"AAAA0MyakcgAAADTraIJMwAAANaOo8HdAAAA2W+fu9sAAADcUJX3RAAAAN8xhnQw" +
	"AAAA4hJxMrUAAADk81Yy6gAAAOfUNXTmAAAA6rUO+MEAAADtleK+kAAAAPB2sMZs" +
	"AAAA81d5EGoAAAD2ODucogAAAPkY+GsqAAAA+/mvfBoAAAD+2mDPiAAAAQG7DGWM" +
	"AAABBJuyPjwAAAEHfFJZrwAAAQpc7Lf8AAABDT2BWToAAAEQHhA9fwAAARL+mWTk" +
	"AAABFd8cz34AAAEYv5p9ZAAAARugEm6tAAABHoCEo3EAAAEhYPEbxgAAASRBV9fD" +
	"AAABJyG4138AAAEqAhQbEAAAASziaaKOAAABL8K5bg8AAAEyowN9qgAAATWDR9F3" +
	"AAABOGOGaYwAAAE7Q79F/wAAAT4j8mbpAAABQQQfzF4AAAFD5Ed2eAAAAUbEaWVL" +
	"AAABSaSFmPAAAAFMhJwRfAAAAU9krM8IAAABUkS30akAAAFVJL0ZdgAAAVgEvKaH" +
	"AAABWuS2ePIAAAFdxKqQzgAAAWCkmO4xAAABY4SBkTQAAAFmZGR57AAAAWlEQahw" +
	"AAABbCQZHNcAAAFt9soZvQAAAXHjtteqAAABdMN9HkQAAAF3oz2rHAAAAXqC+H5J" +
	"AAABfWKtl+IAAAGAQlz3/gAAAYKwfzRYAAABhgGqjBkAAAGI4UjARgAAAYvA4TtS" +
	"AAABjqBz/VIAAAGRgAEGXQAAAZRfiFaLAAABlz8J7fIAAAGaHoXMqgAAAZz9+/LI" +
	"AAABn91sYGMAAAGivNcVkwAAAaWcPBJuAAABqHubVwsAAAGrWvTjgAAAAa46SLfl" +
	"AAABsRmW1FAAAAGz+N842QAAAbbYIeWVAAABubde2psAAAG8lpYYAwAAAb91x53j" +
	"AAABwlTzbFEAAAHFNBmDZQAAAcgTOeM2AAAByvJUi9kAAAHN0Wl9ZwAAAdCweLf1" +
	"AAAB04+CO5oAAAHWboYIbQAAAdlNhB6GAAAB3Cx8ffkAAAHfC28m3wAAAeHqXBlO" +
	"AAAB5MlDVV0AAAHnqCTbIwAAAeqHAKq1AAAB7WXWxCsAAAHwRKcnnQAAAfMjcdUf" +
	"AAAB9gI2zMoAAAH44PYOswAAAfu/r5rzAAAB/p5jcZ4AAAIBfRGSzAAAAgRbuf6U" +
	"AAACBzpctQ0AAAIJwG5iEgAAAgz3kQJqAAACD9YimXwAAAISsH80WAAAAhWTNKjY" +
	"AAACGHG1IVAAAAIbUC/lFwAAAh1qc6ePAAACIQ0UTu4AAAIj6331LAAAAibJ4ecT" +
	"AAACKahAJLsAAAIsI2ebTgAAAi9k64OoAAACMkM4pRsAAAI1IYASqQAAAjf/wcxp" +
	"AAACOiw7DqQAAAI9E+6AWwAAAkA16SIfAAACQ3iPryUAAAJGVrTnNQAAAkftZGv+" +
	"AAACTBLuPZgAAAJO8QJcGgAAAlHPEMeZAAACVJJkTWUAAAJXixyF7gAAAlppGdjw" +
	"AAACXRPugFsAAAJgJQNnFgAAAmKWRTiCAAACZeDWK1MAAAJovrcB8wAAAmuckiZe" +
	"AAACbTL3mKkAAAJxWDdY6wAAAnQ2AWc7AAACdxPFw7AAAAJ58YRuXwAAAnzPPWdh" +
	"AAACfmWArssAAAKCip5EswAAAoVoRikyAAACh72/UlUAAAKLI4TeSgAAAo0T7oBb" +
	"AAACkDXpIh8AAAKSlkU4ggAAApaZvfthAAACmQKjeqsAAAKcVLhkyQAAAp3qvRCD" +
	"AAACog+cC7UAAAKkx2BdYQAAAqe9v1JVAAACqWBW2vwAAAKsPa8U7wAAAq8bAZ7K" +
	"AAACspZFOIIAAAK10CLYDwAAArj6RxyzAAACupAS5xMAAAK9bUkBzAAAAsBKeWz2" +
	"AAACwyekKKYAAALGGl6PTAAAAsjh6JH2AAACy78CP8IAAALOnBY+bgAAAtF5JI4T" +
	"AAAC1FYtLsYAAALXMzAgnQAAAtoQLWOwAAAC3O0k+BQ="

var (
	crushLnLH = mustDecodeBase64(crushLnLHBase64)
	crushLnLL = mustDecodeBase64(crushLnLLBase64)
)

func mustDecodeBase64(value string) []byte {
	decoded, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		panic(err)
	}
	return decoded
}

func tableUint64(table []byte, index uint32) uint64 {
	offset := index * 8
	return uint64(table[offset])<<56 | uint64(table[offset+1])<<48 |
		uint64(table[offset+2])<<40 | uint64(table[offset+3])<<32 |
		uint64(table[offset+4])<<24 | uint64(table[offset+5])<<16 |
		uint64(table[offset+6])<<8 | uint64(table[offset+7])
}

// crushLn computes 2^44*log2(input+1), matching Ceph's fixed-point mapper.
func crushLn(input uint32) uint64 {
	x := input + 1
	exponent := 15
	if x&0x18000 == 0 {
		shift := bits.LeadingZeros32(x&0x1ffff) - 16
		x <<= shift
		exponent -= shift
	}

	coarse := x >> 8
	reciprocal := ((uint64(1) << 55) + uint64(coarse) - 1) / uint64(coarse)
	fraction := (uint64(x) * reciprocal >> 48) & 0xff
	logarithm := tableUint64(crushLnLH, coarse-128) + tableUint64(crushLnLL, uint32(fraction))
	return uint64(exponent)<<44 + logarithm>>(48-44)
}
