[graph]
all-features = false
no-default-features = false

[advisories]
version = 2
yanked = "deny"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
unused-allowed-license = "allow"
allow = ["Apache-2.0", "LGPL-2.1-only", "MIT", "Unicode-3.0", "Unlicense"]
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []